# States
PROJECT_INFO = 0
NEW_BOARD = 2
SET_ACTIVE_BOARD = 5
SET_PROJECT_NAME = 6
REMOVE_BOARD = 3

BOARD_INFO = 7
SET_BOARD_NAME = 11
SET_BOARD_DESCRIPTION = 12
ADD_COLUMN = 13

COLUMN_INFO = 14
SET_COLUMN_NAME = 15
SET_COLUMN_DESCRIPTION = 16
SET_COLUMN_TASK_LIMIT = 20

TASK_INFO = 17
SET_TASK_NAME = 18
SET_TASK_DESCRIPTION = 19

BOARD = 1
ADD_TASK = 21
REMOVE_TASK = 22
MOVE_TASK = 23

# Board view selections
BOARD_SELECT_BOARD = 8
BOARD_SELECT_COLUMN = 9
BOARD_SELECT_TASK = 10
